Iter13
morozoffnor/go-url-shortener pull request #13
Opened 2024-07-16 00:42 UTC by morozoffnor

2024-07-17 14:22 UTC, capsulated commented
> Помимо инкрементов:
> 
> * сделал хендлеры типом
> * вытащил конструкторы из конструкторов
> * вытащил логгер в отдельный пакет
> 
> По логгеру как раз вопрос. Нормально ли для каждого места, где мне нужен логгер создавать новый экземпляр или его лучше иметь глобальной переменной где-то?

Так экземпляр логгера можно передавать в каждый конструктор дроугих объектов - так  нагляднее и проще менеджерить. Но вполне можно и глобальной переменной сделать, будет синглтон в глобальной переменной - вполне распространённый подход (как нативный пакет "log" из go)

2024-07-17 14:49 UTC, capsulated requested changes
Всё в комментариях

2024-07-17 14:49 UTC, capsulated commented on cmd/shortener/main.go
>  	// Создаём бесконечный контекст
Кстати, а почему 'бесконечный'?

2024-07-17 14:49 UTC, capsulated commented on internal/handlers/handlers.go
> +func New(cfg *config.Config, store storage.Storage) *Handlers {
👍

2024-07-17 14:49 UTC, capsulated commented on internal/handlers/handlers.go
> +func (h *Handlers) ShortURLHandler(w http.ResponseWriter, r *http.Request) {
Можно хендлеры и по файлам раскидать. Это сам смотри, как удобнее

2024-07-17 14:49 UTC, capsulated commented on internal/handlers/handlers.go
> +	decodedBody, _ = strings.CutPrefix(decodedBody, "url=")
А это что за префикс? Что-то не вспомню такое разве было в задании?

2024-07-17 14:49 UTC, capsulated commented on internal/handlers/handlers.go
> +	body, err := body.GetBody(r)
Я бы не стал создавать отдельный метод или пакет для чтения body, даже с учётом того, что этот функционал дублируется. Также и с записи результата в response (тоже иногда выносят в функции). Причина простая - немного неудобнее становиться чтение кода логики хендлера

2024-07-17 14:49 UTC, capsulated commented on internal/server/server.go
> +	h := handlers.New(cfg, strg)
А тут создание хендлеров всё равно в конструкторе. Конечно, они относятся к серверу, но фактически, может понадобится к примеру, заменить http сервер - это реальный пример из жизни. Лучше вынести на уровень `cmd` или `app` и передать экземпляр хендлеров уже в конструктор сервера

2024-07-17 14:49 UTC, capsulated commented on internal/storage/db.go
> +func (d *Database) createTable(ctx context.Context) error {
Обычно, это в init.sql в контейнере кладут. Но у нас автотесты) Комментарий для справки

2024-07-17 14:49 UTC, capsulated commented on internal/storage/db.go
> +	for _, v := range urls {
В цикле перебирать записи для batch плохая идея. Нужно использовать инструментарий библиотеки для записи "пачек" записей - чтобы выполнить за один запрос запись пачки. На крайний случай, конкатенировать строку - но это не самое лучшее решение. А ещё есть UPSERT (UPDATE OR INSERT) - погугли для postgres. Количество запросов необходимо минимизировать, в идеале - одни запрос, на крайний случай - два, может вложенный UPDATE bp SELECT в одним запросе, но тоже не желательно. Идеально - всё же один запрос

2024-07-17 14:49 UTC, capsulated commented on internal/storage/db.go
> +	tx, err := d.conn.BeginTx(ctx, nil)
batch  можно без транзакции реализовать и не только можно, а даже желательно

2024-07-17 14:49 UTC, capsulated commented on internal/storage/memory.go
> +func (s *MemoryStorage) Ping(ctx context.Context) bool {
Пустые методы для реализации интерфейса - это антипаттерн. Можно разделить интерфейс: Storage, Pinger, Closer к примеру, и общий составной из них всех. И проверять, реализует ли переданный через интерфейс экземпляр интерфейсу Pinger. Нейминг примерный. Не совсем прям критично, но очень желательно что-то придумать с этим

2024-07-17 14:49 UTC, capsulated commented on pkg/logger/logger.go
> +var Logger = NewLogger()
Вполне можно глобальный логгер сделать, как уже ответил в комментарии. Пример "log" из нативной библиотеке go (или тот же http.server)

2024-07-21 21:21 UTC, morozoffnor commented on internal/storage/db.go
> +	for _, v := range urls {
Посмотрел в интернетах, пишут что есть примерно 3 варианта, как инсертить много строк:

1) CopyFrom в pgx
2) SendBatch в pgx
3) UPSERT в самом postgres
(конкатенацию не учитываю, кажется, будто это для уже совсем отчаявшихся)

3 вариант решил отмести, потому что там для реализации ON CONFLICT советуют делать костыли с временными таблицами, не понравилось мне такое.

Между 1 и 2 вариантами решил выбрать именно 2, потому что там обязательно использование пулов соединений. Просто ради интереса захотелось сделать через пулы. CopyFrom, как пишут, быстрее, конечно, но так не интересно :)

2024-07-21 21:24 UTC, morozoffnor commented on internal/storage/db.go
> +	tx, err := d.conn.BeginTx(ctx, nil)
переделал на встроенный в библиотеку SendBatch

2024-07-21 21:25 UTC, morozoffnor commented on internal/storage/memory.go
> +func (s *MemoryStorage) Ping(ctx context.Context) bool {
убрал везде, добавил проверку на реализацию интерфейса

2024-07-21 21:27 UTC, morozoffnor commented on internal/server/server.go
> +	h := handlers.New(cfg, strg)
вынес на уровень cmd

2024-07-21 21:32 UTC, morozoffnor commented on internal/handlers/handlers.go
> +	body, err := body.GetBody(r)
на прошлом ревью ты как раз [предлагал](https://github.com/morozoffnor/go-url-shortener/pull/9#discussion_r1674808123) вынести это в отдельный пакет, чтобы потом в пет-проекты и тд можно было импортнуть

2024-07-21 21:33 UTC, morozoffnor commented on internal/handlers/handlers.go
> +func (h *Handlers) ShortURLHandler(w http.ResponseWriter, r *http.Request) {
Я думаю пока оставлю так, если их станет больше, то пораскидываю по файлам

2024-07-21 21:45 UTC, morozoffnor commented on internal/handlers/handlers.go
> +	decodedBody, _ = strings.CutPrefix(decodedBody, "url=")
кажется, это остатки каких-то моих костылей. Убрал

2024-07-21 21:47 UTC, morozoffnor commented on pkg/logger/logger.go
> +var Logger = NewLogger()
окей, пусть пока остаётся глобальной переменной тогда, но потом я бы переделал на экземпляры

2024-07-21 21:49 UTC, morozoffnor commented on cmd/shortener/main.go
>  	// Создаём бесконечный контекст
Это я скорее для себя его так описал) context.Background же не имеет дедлайна, никогда сам не отменяется и всё такое.

2024-07-23 00:40 UTC, capsulated commented on cmd/shortener/main.go
>  	// Создаём бесконечный контекст
=))

2024-07-23 00:40 UTC, capsulated commented on internal/handlers/handlers.go
> +func (h *Handlers) ShortURLHandler(w http.ResponseWriter, r *http.Request) {
ок ок

2024-07-23 00:42 UTC, capsulated commented on internal/handlers/handlers.go
> +	body, err := body.GetBody(r)
Если удобно такой воркер-обработчик - то оставляй. Такой helper для body получился

2024-07-23 00:44 UTC, capsulated commented on internal/storage/db.go
> +	for _, v := range urls {
pgx:
https://github.com/jackc/pgx/blob/master/batch_test.go 

ON CONFLICT DO NOTHING или  ON CONFLICT DO UPDATE - там ничего доп создавать не нужно, там есть такой синтаксис в sql

В другой библиотеке sqlx есть batch update https://github.com/jmoiron/sqlx

2024-07-23 00:45 UTC, capsulated commented on internal/storage/db.go
> +	tx, err := d.conn.BeginTx(ctx, nil)
А ну вот супер, они записи пачками есть почти в каждых дарйверах,

2024-07-23 00:45 UTC, capsulated commented on internal/storage/memory.go
> +func (s *MemoryStorage) Ping(ctx context.Context) bool {
Супер, как вариант

2024-07-23 00:46 UTC, capsulated approved these changes
Да, всё супер! 

В следующих спринтах если что, будет что-то рефакторить, если понадобиться

2024-07-23 07:10 UTC, merged