Iter5
morozoffnor/go-url-shortener pull request #5
Opened 2024-06-09 11:19 UTC by morozoffnor

2024-06-11 08:10 UTC, morozoffnor commented on config/main.go
> +		flag.Parse()
Я не знаю можно ли тут задавать вопросы, но я попробую)

Что в курсе, что в репе `pflag` пишут, что это drag-n-drop replacement для дефолтной либы `flag`. Но у меня почему-то оно никак не заводилось. 

`import flag "github.com/.../pflag` просто отказывался хавать `-а` и `-b`.
Поэтому решил остаться на дефолтном `flag`. Может я что-то упускаю?

2024-06-13 20:00 UTC, capsulated requested changes
В принципе решение для первого спринта приемлемо, но к сожалению, никак не расчитано на масштабирование. Хорошо бы создать несколько независимых пакетов: `server`, `handlers`, `config` и тп.

Остаётся три момента: по лишнему клиенту из примера (он не нужен), по указателю/значению, и по потокобезопасность мапы 

По пакетам если успеешь разбить - будет круто, если нет - то можно и в следующих спринтах, там необходимость в этом появится намного острее

2024-06-13 20:00 UTC, capsulated commented on cmd/client/main.go
> +	// контейнер данных для запроса
Комментарии на каждую строку лучше не описывать, но вполне допускаются комментарии в стиле [godoc](https://go.dev/blog/godoc)

2024-06-13 20:00 UTC, capsulated commented on cmd/client/main.go
Клиент для запросов к шортенеру в задании, вроде бы, не было. Локально можно оставить, либо в отдельной ветке, но автотест всё это проверяет, поэтому это лишнее

2024-06-13 20:00 UTC, capsulated commented on config/main.go
Нейминг файла немного вводит в заблуждение. Это пакет файл конфига лучше бы назвать к примеру `server.go`

2024-06-13 20:00 UTC, capsulated commented on internal/app/server.go
> +package app
`app` в данном случае, выглядит избыточно. Лучше на верхнем уровне создавать все пакеты (в корне internal, если они не экспортируются, либо в корне приложения, если экспортируемые). И только в случае, когда необходим именно вложенный пакет - тогда создавать его

2024-06-13 20:00 UTC, capsulated commented on internal/app/server.go
> +func RunServer(addr string, respAddr string) error {
В принципе, в данном спринте решение подходящие, и даже органичное. Но уже в следующих придётся немного рефакторить, так как функционал увеличится

2024-06-13 20:00 UTC, capsulated commented on internal/app/urls.go
> +	s.list[full] = randChars
А тест разве не ругается на race condition? Подсказка: `map` потокобезопасна или нет?

2024-06-13 20:00 UTC, capsulated commented on internal/app/server.go
> +var urlStorage = URLStorage{
Наводящий вопрос: когда назначать значение переменной указателем, а когда значением? (вопрос с подвохом)
```go
var urlStorage = URLStorage{
	list: make(map[string]string),
}
```
VS
```go
var urlStorage = &URLStorage{
	list: make(map[string]string),
}
```

И почему не сделать так:
```go
var urlStorage = make(map[string]string)
```
?

2024-06-14 09:05 UTC, morozoffnor commented on internal/app/urls.go
> +	s.list[full] = randChars
Хм, и правда, мапа не безопасна, если мы что-то записываем. Но при этом ничего на меня не ругается, попробовал даже через `go run -race` прогнать

Тут будет лучше обернуть это всё через `sync` или как-то иначе подойти к этому?

2024-06-15 11:02 UTC, morozoffnor commented on cmd/client/main.go
> +	// контейнер данных для запроса
Удалил клиент

2024-06-15 11:02 UTC, morozoffnor commented on cmd/client/main.go
Удалил клиент

2024-06-15 11:02 UTC, morozoffnor commented on config/main.go
Переименовал

2024-06-15 11:02 UTC, morozoffnor commented on internal/app/server.go
> +package app
перекинул всё на уровень выше

2024-06-15 11:07 UTC, morozoffnor commented on internal/app/server.go
> +var urlStorage = URLStorage{
Интересный вопрос! Насколько я понимаю, в целом назначение значением быстрее указателей. Но при этом, если я хочу к структуре добавить методы, то почему-то внезапно указатель становится быстрее. Вот тут мне, конечно, не ясно почему)

Я поменял на указатель.

Предположу, что нам надо добавлять методы для чтения/записи урлов, а значит нужна струкра) Поэтому нельзя просто сделать `urlStorage` обычной мапой.

2024-06-15 11:16 UTC, morozoffnor commented
> По пакетам если успеешь разбить - будет круто, если нет - то можно и в следующих спринтах, там необходимость в этом появится намного острее

По пакетам тогда разобью постепенно, к следующему ревью

2024-06-17 20:52 UTC, capsulated commented on internal/app/urls.go
> +	s.list[full] = randChars
`syncmap` или `mute` в следующем спринте уже

2024-06-17 20:57 UTC, capsulated commented on internal/app/server.go
> +var urlStorage = URLStorage{
Вопрос с подвохом))) Мапа и так по указателю передаётся. Бывает спрашивают на собеседовании)

По указателю и по значению самим методам разницы нет, они в любом случае будут относится к типу (структуре), а фишка, что при передаче по значению копируется в памяти объект  и его изменения не изменит начальный, а по указателю - передаётся адрес передаваемого экземпляра,  его изменения повлияют на все чтения по этоу указателю

2024-06-17 20:59 UTC, capsulated approved these changes
Всё круто, апрувлю! Пару теоретических коментов оставил

2024-06-18 07:30 UTC, merged