Iter9
morozoffnor/go-url-shortener pull request #9
Opened 2024-06-28 23:47 UTC by morozoffnor

2024-07-01 22:30 UTC, capsulated requested changes
Добавил комментарии, если с чем-то не согласен - однозначная аргументация в ответе на коммент очень приветствуется. На крайний случай 1-1

И не вижу попытки обработки штатного завершения с сохранением текущих обработок. Лучше добавить хоть что-то, а дальше будем развивать )

2024-07-01 22:30 UTC, capsulated commented on internal/storage/urls.go
> +var URLs = newURLStorage()
Глобальные переменные увеличивают "связность" кода. Лучше возвращать указатель на экземпляр. В go отлично видно, сколько экземпляров создано, передавая по указателю, если правильно внедрять зависимости. Поэтому классический ООП выглядит приблизительно так:
```go
// Объект
type Config struct {
   host   string
   port   string
}

// Конструктор, возвращающий указатель на экземпляр
func NewConfig(...) *Config {
	//
	...
	return &Config{
		host: ...,
		port: ...
	}
}

// Методы
func (c *Config) parseFlags(..) { ... }
func (c *Config) parseEnv(..) { ... }

type MemStorage struct {
    ....
}

func NewMemStorgage(...) ...

func (ms *MemStorage) Create(key string, val string) error {
	...
}

func (ms *MemStorage) Read(key string) ([]string, error) {
   ...
}

// Хендлеры
type Storage interface {
   Create(key string, val string) error
   Read(key string) ([]string, error)
}

type MetricHandlers struct {
   store Storage
}


func NewMetricHandlers(store Storage) *MetricHandlers {
   ...
   return &MetricHandlers {
      store: store
   }
}

func (sh *MetricHandlers) someHandler(w http.ResponseWriter, r *http.Request) { 
   sh.store.Create(...)
   ...
}

type Router struct {
   handlers *MetricHandlers
}

func NewRouter(handlers *MetricHandlers) *Router {
	...
	r.Post("/getID", handlers.someHandler)
	r.Get("/", handlers.someHandler)
	...
}
```

А в `app` или `cmd` может выглядеть так:
```go
func main() {
   cfg, err := config.New()
   if err != nil { ... }
   
   store, err := NewMemStorage(cfg)
   if err != nil { ... }

   handlers, err := NewMetricHandlers(cfg, store)
   if err != nil { ... }   
   ...
   // и тп

   go server.ListenAndServe()
   go worker.Run()
   go anotherWorker.Run()
}
```

2024-07-01 22:30 UTC, capsulated commented on internal/storage/urls.go
> +var URLs = newURLStorage()
В принципе, если singelton - тогда оправдать глобальную переменную можно... Но тогда где в приложении опасность создания двух и более экземпляров ?

2024-07-01 22:30 UTC, capsulated commented on internal/storage/urls.go
> +func createRandomCharSeq() string {
Может в отдельном пакете сделать? К примеру, `chargen`? И в `pkg` его хранить

2024-07-01 22:30 UTC, capsulated commented on internal/types/gzip.go
> +func (w GzipWriter) Write(b []byte) (int, error) {
Ресивер передаётся по значению - почему именно так? Нужно обязательно разобраться с этим.

Лайфхак: почти всегда использовать указатель, если однозначно не требуется передача по значению. В большиснтве ЯП дефолтный синтаксис переменных хранит именно указатель

2024-07-01 22:30 UTC, capsulated commented on internal/types/gzip.go
> +package types
А почему имя пакета `types`? Это же вроде `gzip`... Предлагаю также, в `pkg` перенести в независимый пакет, чтобы потом импортировать в других приложениях

2024-07-01 22:30 UTC, capsulated commented on internal/server/server.go
> +	r := chi.NewRouter()
Тут очень намешано получилось. Лучше сделать отдельно сущность севера, ему в конструктор передать уже созданные экземпляры хендлера и/или роутера, конфиги, и создать свой сервер. Можно либо "встроить" или использовать композицию (на примере router):

```go
// Встраивание - аналог настледовани
type EmbeddedRouter {
   *chiMux
}

// Встраивание - аналог настледовани
type ComposedRouter {
   mux *chiMux
}
```

Но назначение роутеров и хендлеров рядом со стартом сервера точно не должно быть в одном методе

2024-07-01 22:30 UTC, capsulated commented on internal/types/logResponseWriter.go
> +package types
Посмотри хороший пример, как организованы middleware у [chi](https://github.com/go-chi/chi/tree/master/middleware). Нужно по такому же принципу сделать

2024-07-01 22:30 UTC, capsulated commented on internal/middlewares/compression.go
> +package middlewares
Миддлвари можно из internal перенести или вообще в `pkg`

2024-07-01 22:30 UTC, capsulated commented on internal/handlers/handlers.go
> +	url, err := storage.URLs.AddNewURL(decodedBody)
Вообще даже не ясно, где инициализация storage. По привычке пытаюсь найти конструктор, так как это классический подход, и должно быть где-то `storage.New()`. А с глобальными переменными становиться всё не так наглядно =( С небольшими хелперами это может и ок, но точно не для хранилки

2024-07-01 22:30 UTC, capsulated commented on internal/handlers/handlers.go
> +func FullURL(w http.ResponseWriter, r *http.Request) {
И назначить бы эти функции к какому-то типу, чтобы стали методами типа. Тогда внедрение зависимости storage и тп будет намного проще и гибче

2024-07-10 21:40 UTC, morozoffnor commented on internal/config/config.go
> +func NewConfig() ServerConfig {
поменял всё на указатели

2024-07-10 21:41 UTC, morozoffnor commented on internal/config/flags.go
> +func init() {
убрал иниты, в т.ч. в тестах

2024-07-10 21:41 UTC, morozoffnor commented on internal/config/flags.go
> +var Flags = ServerConfigFlags{}
поменял всё на указатели

2024-07-10 21:41 UTC, morozoffnor commented on internal/handlers/body.go
> +func GetBody(r *http.Request) ([]byte, error) {
перенёс в pkg

2024-07-10 21:42 UTC, morozoffnor commented on internal/storage/urls.go
> +var URLs = newURLStorage()
Поменял всё на функции, возвращающие экземпляры

2024-07-10 21:42 UTC, morozoffnor commented on internal/storage/urls.go
> +func createRandomCharSeq() string {
перенёс

2024-07-10 21:43 UTC, morozoffnor commented on internal/types/gzip.go
> +func (w GzipWriter) Write(b []byte) (int, error) {
тут просто какой-то странный затуп с ресивером, поменял

2024-07-10 21:43 UTC, morozoffnor commented on internal/types/gzip.go
> +package types
перенёс

2024-07-10 21:44 UTC, morozoffnor commented on internal/server/server.go
> +	r := chi.NewRouter()
разделил создание сервера и создание роутера в отдельные функции

2024-07-10 21:48 UTC, morozoffnor commented on internal/types/logResponseWriter.go
> +package types
Может я чего-то не понимаю, но полистав миддлвари у chi пришел к выводу, что они там по-разному реализованы) 

Переделал так, чтобы они возвращали хендлеры, но не уверен что именно ты имел в виду)

2024-07-10 21:48 UTC, morozoffnor commented on internal/middlewares/compression.go
> +package middlewares
перенёс

2024-07-10 21:49 UTC, morozoffnor commented on internal/handlers/handlers.go
> +	url, err := storage.URLs.AddNewURL(decodedBody)
убрал глобальные переменные, сторадж сосдаётся теперь один раз и передаётся по указателю везде, где нужно

2024-07-10 21:53 UTC, morozoffnor commented on internal/handlers/handlers.go
> +func FullURL(w http.ResponseWriter, r *http.Request) {
не очень понял зачем мне это нужно)

типа чтобы я мог сделать условно вот так?
```go
storage.FullUrl(w, r)
```

2024-07-10 21:57 UTC, morozoffnor commented
Ух, пришлось неплохо так перелопатить проект. Везде поменял всё на указатели и конструкторы.
> И не вижу попытки обработки штатного завершения с сохранением текущих обработок. 

Добавил грейсфул завершение работы через горутины и waitgroup'ы. Мы пока в курсе не доходили до такого, так что не уверен, что именно так такое обычно и реализовывается.

2024-07-11 22:36 UTC, capsulated commented on cmd/shortener/main.go
> +	flag.Parse()
Парсинг флагов тогда уже тоже в пакет конфига перенести

2024-07-11 22:36 UTC, capsulated commented on cmd/shortener/main.go
> +	g, gCtx := errgroup.WithContext(ctx)
Выглядит, вроде, корректно. Отдельный плюс за то, что добавил обаботку сигналов и выключение срвера. Так `errgroup` ещё не проходили (как и `waitgraoup`, которые будут в 4ом спринте), то в течение спринтов можно будет ещё дорабатывать gracefully shotdown. 

По идее, надо ещё добавить обработку отключения подключения к БД и файлам, если они есть, добавив методы завершения в этих пакетах. И можно сделать один `select` в конце программы, который будет обрабатывать сигналы системы. Я разберу этот кейс на вебинаре

2024-07-11 22:36 UTC, capsulated commented on internal/config/flags.go
> +func init() {
В тестах можно оставлять, если упрощают жизнь, так как там всё на виду. `init` в корне теста вообще не проблема

2024-07-11 23:16 UTC, capsulated approved these changes
Всё хорошо, но по структуре надо ещё немного распределить некоторые типы и конструкторы.

Комментарии все написал в примерами. Так как уже дедлайн, апрувлю, но надо обязательно пофиксить в начале выполнения след спринта. Если вдруг будут вопросы - записывайся 1-1. Если вдруг слотов не будет - пиши в директ по поводу именно звонка

2024-07-11 23:16 UTC, capsulated commented on internal/handlers/handlers.go
> +func NewShortURLHandler(cfg *config.ServerConfig, s *storage.URLStorage) http.HandlerFunc {
Всё же пора переносить все хендлеры в один тип, чтобы не передавать зависимость на хранилку в каждый хендлер, а только в конструктор. В таком виду будет удобнее управлять объектом. Приблизительный пример:
```go
type MemStorage struct {
    ....
}

func NewMemStorgage(...) ...
func (ms *MemStorage) Create(key string, val string) error {...}
func (ms *MemStorage) Read(key string) ([]string, error) {...}

// Хендлеры
type Handlers struct {
   store Storage
}

type Storage interface {
   Create(key string, val string) error
   Read(key string) ([]string, error)
}

func NewHandlers(store Storage) *Handlers {
   ...
   return &Handlers{
      store: store
   }
}

func (h *Handlers) someHandler(w http.ResponseWriter, r *http.Request) { 
   h.store.Create(...)
   ...
}


type Router struct {
   *chi.Mux
   handlers *Handlers
}

func NewRouter(handlers *Handler) *Router {
        r := chi.NewMux()
	...
	r.Post("/", handlers.someHandler)
	r.Get("/id", handlers.someHandler)
	...
}
```

2024-07-11 23:16 UTC, capsulated commented on internal/handlers/handlers.go
> +			http.Error(w, "Fail during serializing", http.StatusInternalServerError)
`return` потерялся?

2024-07-11 23:16 UTC, capsulated commented on internal/server/server.go
> +	strg := storage.New(cfg)
Хранилку надо бы создать уровнем выше и передать в параметр конструктора, так как конструктор в конструкторе - плохая практика, из-за того, что увеличивается связность сущностей

А вообщем, очень круто, что разобрался, как создать собственный экземпляр http сервера 💪

Можно его также расширить, с помощью встраивания (см комент выше)

2024-07-11 23:16 UTC, capsulated commented on internal/storage/urls.go
> +func New(cfg *config.ServerConfig) *URLStorage {
Конструктор также, NewURLStotrage в данном случае подходящее имя

2024-07-11 23:16 UTC, capsulated commented on pkg/body.go
Классно, что вынес, но для этого также пакет создать надо, чтобы в корне pkg не лежало

2024-07-11 23:16 UTC, capsulated commented on pkg/chargen/chargen.go
Вот, тут круто всё. Для `pkg/body.go` подобный пакет создать по-хорошему

2024-07-11 23:16 UTC, capsulated commented on pkg/middlewares/logging.go
> +var Logger = NewLogger()
А сам логгер-то должен быть в отдельном пакете. А в миддлваре должен быть как внешняя зависимость

2024-07-12 04:46 UTC, merged